[workspace]
members = [".", "metadata"]

[package]
name = "cargo-contract"
version = "0.9.1"
authors = ["Parity Technologies <admin@parity.io>"]
build = "build.rs"
edition = "2018"

license = "GPL-3.0"
readme = "README.md"
repository = "https://github.com/paritytech/cargo-contract"
documentation = "https://substrate.dev/substrate-contracts-workshop/#/"
homepage = "https://www.parity.io/"
description = "Setup and deployment tool for developing Wasm based smart contracts via ink!"
keywords = ["wasm", "parity", "webassembly", "blockchain", "edsl"]
categories = ["command-line-utilities", "development-tools::build-utils", "development-tools::cargo-plugins"]
include = ["Cargo.toml", "src/**/*.rs", "README.md", "LICENSE", "build.rs", "templates"]

[dependencies]
env_logger = "0.8.3"
anyhow = "1.0.38"
structopt = "0.3.20"
log = "0.4.14"
heck = "0.3.2"
zip = { version = "0.5.10", default-features = false }
pwasm-utils = "0.17.0"
parity-wasm = "0.42.1"
cargo_metadata = "0.12.3"
codec = { package = "parity-scale-codec", version = "2.0.0", features = ["derive"] }
which = "4.0.2"
colored = "2.0.0"
toml = "0.5.8"
rustc_version = "0.3.3"
blake2 = "0.9.1"
contract-metadata = { version = "0.2.0", path = "./metadata" }
semver = { version = "0.11.0", features = ["serde"] }
serde = { version = "1.0.123", default-features = false, features = ["derive"] }
serde_json = "1.0.62"
tempfile = "3.2.0"
url = { version = "2.2.1", features = ["serde"] }
binaryen = { version = "0.12.0", optional = true }
impl-serde = "0.3.1"


# dependencies for optional extrinsics feature
async-std = { version = "1.9.0", optional = true }
sp-core = { version = "2.0.1", optional = true }
subxt = { version = "0.14.0", package = "substrate-subxt", optional = true }
futures = { version = "0.3.13", optional = true }
hex = { version = "0.4.2", optional = true }

# Should be removed once bitvecto-rs/bitvec#105 is resolved
funty = "=1.1.0"

[build-dependencies]
anyhow = "1.0.38"
zip = { version = "0.5.10", default-features = false }
walkdir = "2.3.1"

[dev-dependencies]
assert_matches = "1.5.0"
pretty_assertions = "0.6.1"
wabt = "0.10.0"

[features]
default = []
binaryen-as-dependency = ["binaryen"]

# Enable this for (experimental) commands to deploy, instantiate and call contracts.
#
# Disabled by default
extrinsics = ["sp-core", "subxt", "async-std", "futures", "hex"]

# Enable this to execute long running tests, which usually are only run on the CI server
#
# Disabled by default
test-ci-only = []
